server:
  port: 8080
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8
file:
  upload.path: C:/Users/lenovo/Desktop/demo/src/main/resources/static/img/
  upload.path.relative: /img/*

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/book_info?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

mybatis:
  mapper-locations: classpath:mapper/*.xml

pagehelper:
  helper-dialect: mysql
